[default]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10

[development]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10

[testing]
ENVIRONMENT = "testing"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
