[default]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 3
USE_CENTRALIZED_PEER_REGISTRY = true
LOCAL_DB = "db/client.db"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1048576
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"

[development]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 3
USE_CENTRALIZED_PEER_REGISTRY = true
LOCAL_DB = "db/client.db"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1048576
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"

[testing]
ENVIRONMENT = "testing"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 3
USE_CENTRALIZED_PEER_REGISTRY = true
LOCAL_DB = "db/client.db"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1024
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"
