[default]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
SERVER_DB = "db/server.db"

[development]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
SERVER_DB = "db/server.db"

[testing]
ENVIRONMENT = "testing"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
SERVER_DB = ":memory:"
