[default]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 3
SERVER_DB = "db/server.db"
LOCAL_DB = "db/client.db"
REMOTE_SERVER_URL = "http://localhost:5555"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1048576
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"

[development]
ENVIRONMENT = "dev"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
SERVER_DB = "db/server.db"
LOCAL_DB = "db/client.db"
REMOTE_SERVER_URL = "http://localhost:5555"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1048576
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"

[testing]
ENVIRONMENT = "testing"
DISCOVERY_PORT = 12345
DISCOVERY_PING_INTERVAL = 10
SERVER_DB = ":memory:"
LOCAL_DB = "db/client.db"
REMOTE_SERVER_URL = "http://localhost:5555"
CLIENTS_PER_PEER = 1
CHUNK_SIZE =  1024
CHUNK_HASH_FUNC = "md5"
STORAGE_FOLDER = "storage"
METADATA_FOLDER = "metadata"
